# Generated by Django 4.2.18 on 2026-06-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('codigo', models.IntegerField(help_text='Código do Título', primary_key=True, serialize=False)),
                ('descricao', models.CharField(help_text='Informe a descrição do Título', max_length=70)),
            ],
        ),
    ]
